language: node_js
node_js:
  - 4.1.1
addons:
  firefox: "latest"
  chrome: "latest"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm install -g codeclimate-test-reporter
  - gulp init
script:
  - gulp build
  - gulp lint
  - gulp test
  - codeclimate-test-reporter < coverage/lcov.info
